title = "Oddlark"
baseURL = "https://oddlark.com"
tags = ["gamedev", "game", "games", "game development", "oddlark", "odd lark", "humanoib", "spore", "indie", "game studio", 
    "video game", "videogame", "australia", "josh bradbury"]
languageCode = "en-US"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "oddlark"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
author = "Oddlark"
description = "Oddlark is an ultra small and agile development team based in Naarm (Melbourne) helmed by Josh Bradbury + friends with a focus on creating ‘quality oddities’ with a small scope and large impact"
logoBig = "/images/Oddlark2_Alpha.png"
logoSmall = "/images/Oddlark2_Alpha.png"
favicon = "favicon.ico"
opengraphImage = "/images/Oddlark2_Alpha.png"
email = "oddlark+josh.alan.b@gmail.com"
googleTagManager = ""
customCSS = true

# Social media links in footer
twitter = "oddlark"

# Copyright and theme author credit in footer
copyright = true
credit = false

# Cache busting of static resources (additional set up required)
cacheBustCSS = true
cacheBustJS = true

# Code highlighting with highlight.js
highlightJS = true
highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

# Choose either Formspree contact form or Basin contact form
ajaxFormspree = false
ajaxFormspreeGold = false
ajaxBasin = "https://usebasin.com/f/85afb2fd9d9a"

# Lazy loading with lazysizes
lazyloading = true

[[menu.main]]
name = "About"
url  = "/#about"
weight = 1
[[menu.main]]
name = "Who?!"
url  = "/who"
weight = 3