baseURL = "https://oddlark.com"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "Oddlark"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "/images/oddlark-grad.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["/images/oddlark-w-nebula.png"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Oddlark - Quality Oddities"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Creating Quality Oddities"

    # Show a menu of languages available
    language_menu = false

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = false

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Oddlark"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = true

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q90 lanczos photo"
    
    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = true

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "gamedev, game, games, game development, indie games, independent, melbourne, oddlark, odd lark, humanoib, noib, noibs, spore, creature creator, indie, game studio, video game, videogame, australia, josh bradbury, kelsey gamble, felix colgrave, zoe medcraft, wombot, wombot studio, bud builder battler, quality oddities"

    #[[params.contacts]]
    #    label = "email"
    #    value = "hello@oddlark.com"
    #    url = "mailto:hello@oddlark.com"
    #    icon = "fa fa-envelope"

    # Add additional contacts here!
    [[params.contacts]]
            label = "steam"
            value = "steam"
            url = "https://store.steampowered.com/dev/oddlark"
            icon = "fa-brands fa-steam"
    
    [[params.contacts]]
        label = "bluesky"
        value = "oddlark"
        url = "https://bsky.app/profile/oddlark.com"
        icon = "fa-brands fa-bluesky"
        
    [[params.contacts]]
            label = "linkedin"
            value = "linkedin"
            url = "https://www.linkedin.com/company/oddlark/"
            icon = "fa-brands fa-linkedin"

# Define additional languages
[languages]
  [languages.en]
    weight = 10
    languageName = "English"
    contentDir = "content/en"
    
[markup.goldmark.renderer]
unsafe= true